Repository Picktartup/Picktartup-coinservice, pull requests merged in 2024-12, with the labels that each got.

#16 fix: 토큰 현금화 시 request dto 수정
  src/main/java/com/picktartup/coinservice/controller/CoinController.java
  src/main/java/com/picktartup/coinservice/dto/CoinExchangeRequest.java
  src/main/java/com/picktartup/coinservice/service/CoinService.java
  src/main/java/com/picktartup/coinservice/service/CoinServiceImpl.java
Labels: bug

#17 fix: 결제 검증 로직(중복) 제거 및 PaymentDto 수정
  src/main/java/com/picktartup/coinservice/controller/CoinController.java
  src/main/java/com/picktartup/coinservice/dto/PaymentDto.java
  src/main/java/com/picktartup/coinservice/service/CoinService.java
  src/main/java/com/picktartup/coinservice/service/CoinServiceImpl.java
Labels: bug

#18 chore: 온프레미스 서버 주소 변경
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: chore

#19 chore: 온프레미스 서버 주소 재변경
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: chore

#21 Feature/coin/add logging aop
  build.gradle
  src/main/java/com/picktartup/coinservice/CoinApplication.java
  src/main/java/com/picktartup/coinservice/aop/CoinLoggingAspect.java
Labels: enhancement

#24 fix: 환경변수 호출 방식 변경
  src/main/java/com/picktartup/coinservice/service/CoinServiceImpl.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: bug

#23 ✨ feat: AOP 추가 (API 응답 시간, http_method 등등
  src/main/java/com/picktartup/coinservice/aop/CoinLoggingAspect.java
Labels: enhancement

#26 fix: 온프레미스 서비스 통신 시 SSL 인증서 적용
  src/main/java/com/picktartup/coinservice/common/config/WebClientConfig.java
Labels: enhancement
